parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: ~
    database_name: portfolio
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: ~
    mailer_user: ~
    mailer_password: ~
    locale: en
    secret: 61647e5388f185c578f5a6aa658710a7f
    database_path: ~
    img_upload_dir: img/uploads
    contact_email: ~
    registration_enabled: false