fish_front_end:
    resource: "@FishFrontEndBundle/Controller/"
    type:     annotation
    prefix:   /

fish_user:
    resource: "@FishUserBundle/Controller/"
    type:     annotation
    prefix:   /

fish_portfolio:
    resource: "@FishPortfolioBundle/Controller/"
    type:     annotation
    prefix:   /
    
_imagine:
    resource: .
    type:     imagine

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
